version: 1-{branch}+{build}

build_script:
  - cmd: C:\MinGW\msys\1.0\bin\make
  - cmd: rmdir /s /q .git
before_test:
  - cmd: set PATH=%PATH%;C:\Program Files\erl8.3\erts-8.3\bin
test_script:
  - cmd: C:\MinGW\msys\1.0\bin\make --keep-going test_windows

configuration: Test

matrix:
  allow_failures:
    - configuration: Test