version: 1-{branch}+{build}

install:
  - cinst erlang --version=21.0
  - refreshenv

shallow_clone: true

build_script:
  - cmd: C:\MinGW\msys\1.0\bin\make
  - cmd: rmdir /s /q .git
test_script:
  - cmd: C:\MinGW\msys\1.0\bin\make --keep-going test_windows

environment:
  ELIXIR_ASSERT_TIMEOUT: 2000

matrix:
  allow_failures:
    - platform: x86
    - platform: x64
    - platform: Any CPU
