# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: CI for Markdown content

on:
  push:
    branches:
      - "main"
    paths:
      - "lib/**/*.md"
  pull_request:
    paths:
      - "lib/**/*.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Markdown content

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 10

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@30a0e04f1870d58f8d717450cc6134995f993c63 # v21.0.0
        with:
          globs: |
            lib/elixir/pages/**/*.md
            README.md
