# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: CI for Markdown content

on:
  push:
    branches:
      - "main"
    paths:
      - "lib/**/*.md"
  pull_request:
    paths:
      - "lib/**/*.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Markdown content

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 10

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          globs: |
            lib/elixir/pages/**/*.md
            README.md
