# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: Markdown Content

on:
  push:
    branches:
      - "main"

    paths: &paths-filter
      - "**/*.md"
      - .github/workflows/ci-markdown.yml
      - .markdownlint-cli2.jsonc

  pull_request:
    paths: *paths-filter

  workflow_dispatch:

permissions:
  contents: read

env:
  LANG: C.UTF-8

jobs:
  lint:
    name: Lint Markdown content
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@30a0e04f1870d58f8d717450cc6134995f993c63 # v21.0.0
