name: CI for Markdown content

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lib/**/*.md'
  pull_request:
    paths:
      - 'lib/**/*.md'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Markdown content

    strategy:
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v18.0.0
        with:
          globs: |
            lib/elixir/pages/**/*.md
            README.md
