on: check_suite
name: CI email
jobs:
  sendEmail:
    name: Send email
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: docker://fertapric/elixir-ci-email:latest
      env:
        APP_NAME: Cirrus CI
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAIL_FROM: ci@elixir-lang.org
        MAIL_HOST: smtp.sendgrid.net
        MAIL_PASSWORD: ${{ secrets.CI_EMAIL_PASSWORD }}
        MAIL_USERNAME: ${{ secrets.CI_EMAIL_USERNAME }}
