# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: Markdown Content

on:
  push:
    branches:
      - "main"

    paths: &paths-filter
      - "**/*.md"
      - .github/workflows/markdown.yml
      - .markdownlint-cli2.jsonc

  pull_request:
    paths: *paths-filter

  workflow_dispatch:

permissions:
  contents: read

env:
  LANG: C.UTF-8

jobs:
  lint:
    name: Lint Markdown content
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
