# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

name: Notify

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 50
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: "27.3"
          elixir-version: "1.18.3"
      - name: Run Elixir script
        env:
          ELIXIR_FORUM_TOKEN: ${{ secrets.ELIXIR_FORUM_TOKEN }}
          ELIXIR_LANG_ANN_TOKEN: ${{ secrets.ELIXIR_LANG_ANN_TOKEN }}
        run: |
          elixir .github/workflows/notify.exs ${{ github.ref_name }}
